# Generated by Django 3.0.3 on 2020-02-10 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('voivodeship', models.TextField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('category', models.ManyToManyField(to='Min1.Category')),
            ],
        ),
    ]
