# Generated by Django 3.0.3 on 2020-02-10 22:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Min1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='added_by',
            field=models.CharField(max_length=64, verbose_name='Dodano przez'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='category',
            field=models.ManyToManyField(to='Min1.Category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Edytowano'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Dane geograficzne'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='is_active',
            field=models.BooleanField(verbose_name='Czy dalej aktywna?'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='voivodeship',
            field=models.TextField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], verbose_name='Województwo'),
        ),
    ]
