# Generated by Django 3.0.3 on 2020-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Min1', '0002_auto_20200210_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
