# Generated by Django 3.0.3 on 2020-02-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Min1', '0003_mine_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mine',
            name='images',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='voivodeship',
            field=models.CharField(choices=[('1', 'dolnośląskie'), ('2', 'kujawsko-pomorskie'), ('3', 'lubelskie'), ('4', 'lubuskie'), ('5', 'łódzkie'), ('6', 'małopolskie'), ('7', 'mazowieckie'), ('8', 'opolskie'), ('9', 'podkarpackie'), ('10', 'podlaskie'), ('11', 'pomorskie'), ('12', 'śląskie'), ('13', 'świętokrzyskie'), ('14', 'warmińsko-mazurskie'), ('15', 'wielkopolskie'), ('16', 'zachodniopomorskie'), ('17', '-')], max_length=30, verbose_name='Województwo'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
