# Generated by Django 3.0.3 on 2020-02-27 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Min1', '0004_auto_20200227_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(null=True, verbose_name='Komentarz'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Utworzono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Użytkownik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Utworzono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Tytuł'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(verbose_name='Tekst'),
        ),
    ]
