# Generated by Django 3.0.3 on 2020-02-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Min1', '0005_auto_20200227_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
