# Generated by Django 3.0.3 on 2020-02-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Min1', '0006_auto_20200228_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='Nick'),
        ),
    ]
